<?php namespace app\modules\api\models;

class Trip extends \app\models\Trip
{
    const
        STATUS_PENDING = 1,
        STATUS_TRIP = 2,
        STATUS_ENDED = 3,
        STATUS_CANCELED = 4;

    protected $oldStatus;

    public function getUser()
    {
        return Users::findOne($this->user_id);
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        if ($this->status != $this->oldStatus && $this->status == self::STATUS_TRIP)
        {
            // TODO: Отправка подтверждения о выезде
        }
    }

    public function beforeSave($insert)
    {
        $this->oldStatus = $this->getOldAttribute('status');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}