<?php

namespace app\modules\admin\assets;

use yii\web\AssetBundle;

class AppAssetOld extends AssetBundle
{
    public $basePath = '@webroot/modules/admin/assets';
    public $baseUrl = '@web/admin_assets';
    public $css = [
        'css/theme-5/bootstrap.css',
        'css/theme-5/materialadmin.css',
        'css/theme-5/font-awesome.min.css',
        'css/theme-5/material-design-iconic-font.min.css',
        'css/theme-5/libs/nestable/nestable.css',
        'css/theme-default/libs/bootstrap-tagsinput/bootstrap-tagsinput.css',
        'css/theme-5/libs/bootstrap-datepicker/datepicker3.css',
        //'css/theme-5/libs/daterangepicker/daterangepicker.css',
        'css/theme-5/libs/select2/select2.css',
			'css/jquery-ui.min.css',
			'css/all.css',
    ];
    public $js = [
		//'js/libs/jquery/jquery-1.11.2.min.js',
		//'js/libs/jquery/jquery-migrate-1.2.1.min.js',

        'https://maps.googleapis.com/maps/api/js?key={params_gmaps_key_admin}&libraries=places&v=3.exp&language=ru',
        'js/gmaps/markerwithlabel.js',
        'js/gmaps/mclusters.js',
        'js/gmaps/map.js',
		'js/libs/bootstrap/bootstrap.min.js',
		'js/libs/spin.js/spin.min.js',
		'js/libs/autosize/jquery.autosize.min.js',
		'js/libs/nestable/jquery.nestable.js',
		'js/libs/nanoscroller/jquery.nanoscroller.min.js',
		'js/libs/inputmask/jquery.inputmask.bundle.min.js',
		'js/libs/bootstrap-tagsinput/bootstrap-tagsinput.min.js',
		'js/libs/typeahead/typeahead.jquery.min.js',
		'js/libs/bootstrap-datepicker/bootstrap-datepicker.js',
		'js/libs/moment/moment.js',
        'js/libs/daterangepicker/daterangepicker.js',
		'js/libs/select2/select2.min.js',
		'js/core/source/App.js',
		'js/core/source/AppNavigation.js',
		'js/core/source/AppOffcanvas.js',
		'js/core/source/AppCard.js',
		'js/core/source/AppForm.js',
		'js/core/source/AppNavSearch.js',
		'js/core/source/AppVendor.js',
		'js/core/demo/Demo.js',
		'js/core/demo/DemoUILists.js',
			'js/jquery-ui.min.js',
			'js/jquery.mjs.nestedSortable.js',
			'js/all.js',
    ];
	public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',	
    ];

    public  function init()
    {
        $replace = [
            '{params_gmaps_key_admin}' => \Yii::$app->params['gmaps']['key']['admin'],
        ];
        $this->js = implode('_@_', $this->js);
        $this->js = str_replace(array_keys($replace), array_values($replace), $this->js);
        $this->js = explode('_@_', $this->js);
        parent::init(); // TODO: Change the autogenerated stub
    }

}