<?php namespace app\modules\api\controllers;

use app\models\Checkpoint;
use app\models\Line;
use app\modules\api\models\Trip;
use app\modules\api\models\Users;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

use app\modules\api\models\City;

/** @property \app\modules\api\Module $module */
class LineController extends BaseController
{
    public $modelClass = 'app\modules\api\models\RestFul';

    public function init()
    {
        parent::init();

        $authHeader = Yii::$app->request->getHeaders()->get('Authorization');
        if ($authHeader !== null && preg_match('/^Bearer\s+(.*?)$/', $authHeader, $matches)) $this->token = $matches[1];
        else $this->module->setError(403, '_token', "Token required!");
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'startpoints', 'endpoints', 'checkpoints',
                            'update-line', 'passengers', 'seats',
                            'cancel'
                        ],
                        'allow' => true
                    ]
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'startpoints'  => ['GET'],
                    'endpoints'  => ['GET'],
                    'checkpoints'  => ['GET'],
                    'passengers'  => ['GET'],
                    'seats'  => ['GET'],
                    'update-line'  => ['PUT'],
                    'cancel' => ['DELETE']
                ]
            ]
        ];
    }

    public function beforeAction($event)
    {
        $user = $this->TokenAuth(self::TOKEN);
        if ($user) $user = $this->user;

        /**
         * Проверка прав на тип пользователя. Должен быть водителем, для доступа к методам
         */
        if ($user->type != Users::TYPE_DRIVER)
            $this->module->setError(403, 'user', "User has no privileges");

        return parent::beforeAction($event); // TODO: Change the autogenerated stub
    }

    public function actionStartpoints()
    {
        $user = $this->TokenAuth(self::TOKEN);
        if ($user) $user = $this->user;

        $points = [];

        $startpoints = Checkpoint::find()->where(['type' => Checkpoint::TYPE_START])->all();
        if ($startpoints && count($startpoints) > 0) foreach ($startpoints as $point)
        {
            /** @var $point \app\models\Checkpoint */
            $points[] = $point->toArray();
        }

        $this->module->data = $points;
        $this->module->setSuccess();
        $this->module->sendResponse();
    }

    public function actionEndpoints()
    {
        $user = $this->TokenAuth(self::TOKEN);
        if ($user) $user = $this->user;

        $points = [];

        $endpoints = Checkpoint::find()->where(['type' => Checkpoint::TYPE_END])->all();
        if ($endpoints && count($endpoints) > 0) foreach ($endpoints as $point)
        {
            /** @var $point \app\models\Checkpoint */
            $points[] = $point->toArray();
        }

        $this->module->data = $points;
        $this->module->setSuccess();
        $this->module->sendResponse();
    }

    public function actionCheckpoints()
    {
        $user = $this->TokenAuth(self::TOKEN);
        if ($user) $user = $this->user;

        $points = [];

        $checkpoints = Checkpoint::find()->where(['type' => Checkpoint::TYPE_STOP])->all();
        if ($checkpoints && count($checkpoints) > 0) foreach ($checkpoints as $point)
        {
            /** @var $point \app\models\Checkpoint */
            $points[] = $point->toArray();
        }

        $this->module->data = $points;
        $this->module->setSuccess();
        $this->module->sendResponse();
    }

    public function actionSeats($id)
    {
        $user = $this->TokenAuth(self::TOKEN);
        if ($user) $user = $this->user;

        /** @var \app\models\Line $line */
        $lines = Line::find()->andWhere(['AND', ['=', 'route_id', $id]])->all();
        if (!$lines) $this->module->setError(422, '_line', "Not Found");

        $seats = 0;
        $free_seats = 0;

        foreach ($lines as $line)
        {
            $seats += $line->seats;
            $free_seats += $line->freeseats;
        }

        $this->module->data['seats'] = $seats;
        $this->module->data['free_seats'] = $free_seats;
        $this->module->setSuccess();
        $this->module->sendResponse();
    }

    public function actionPassengers($id)
    {
        $user = $this->TokenAuth(self::TOKEN);
        if ($user) $user = $this->user;

        $passengers = Trip::find()->where(['route_id' => $id])->all();
        if (!$passengers) $this->module->setError(422, 'trip', "Not Found");

        $_passengers = [];
        /** @var \app\models\Trip $passenger */
        foreach ($passengers as $passenger) $_passengers[] = $passenger->user->toArray();

        $this->module->data['passengers'] = $_passengers;
        $this->module->setSuccess();
        $this->module->sendResponse();
    }

    public function actionUpdateLine($id)
    {
        $user = $this->TokenAuth(self::TOKEN);
        if ($user) $user = $this->user;

        $line = $this->getLine($id);
        if (!$line) $this->module->setError(422, '_line', "Not Found");

        $this->prepareBody();
        $this->validateBodyParams(['freeseats', 'seats']);

        $line->freeseats = intval($this->body->freeseats);
        $line->seats = intval($this->body->seats);

        if (!$line->validate() || !$line->save())
        {
            if ($line->hasErrors())
            {
                foreach ($line->errors as $field => $error_message)
                    $this->module->setError(422, 'line.' . $field, $error_message, true, false);
                $this->module->sendResponse();
            }
            else $this->module->setError(422, 'line', "Can't validate line model from data.");
        }

        $this->module->data['line'] = $line->toArray();
        $this->module->setSuccess();
        $this->module->sendResponse();
    }

    public function actionCancel($id)
    {
        $user = $this->TokenAuth(self::TOKEN);
        if ($user) $user = $this->user;

        $this->prepareBody();
        $this->validateBodyParams(['cancel_reason_trip', 'cancel_reason_line']);

        /** @var \app\models\Line $line */
        $line = Line::findOne($id);
        if (!$line) $this->module->setError(422, '_line', "Not Found");

        /** @var \app\models\Trip $trip */
        $trips = Trip::find()->andWhere(['route_id' => $line->route_id, 'vehicle_id' => $line->vehicle_id, 'driver_id' => $line->driver_id])->all();
        if (!$trips) $this->module->setError(422, '_trip', "Not Found");

        $line->cancel_reason = $this->body->cancel_reason_line;
        $line->status = Line::STATUS_CANCELED;

        if (!$line->validate() || !$line->save())
        {
            if ($line->hasErrors())
            {
                foreach ($line->errors as $field => $error_message)
                    $this->module->setError(422, 'line.' . $field, $error_message, true, false);
                $this->module->sendResponse();
            }
            else $this->module->setError(422, 'line', "Can't validate model from data.");
        }

        $trip_errors = 0;
        $_trips = [];
        foreach ($trips as $trip)
        {
            $trip->cancel_reason = $this->body->cancel_reason_trip;
            $trip->status = Trip::STATUS_CANCELED;

            if (!$trip->validate() || !$trip->save())
            {
                if ($trip->hasErrors())
                {
                    foreach ($trip->errors as $field => $error_message)
                    {
                        $this->module->setError(422, 'trip.' . $field, $error_message, true, false);
                        $trip_errors++;
                    }
                }
                else $this->module->setError(422, 'trip', "Can't validate model from data.");
            }

            $_trips[] = $trip->toArray();
        }

        if ($trip_errors > 0) $this->module->sendResponse();

        $this->module->data['line'] = $line->toArray();
        $this->module->data['trips'] = $_trips;
        $this->module->setSuccess();
        $this->module->sendResponse();
    }

    protected function getLine($line_id)
    {
        return Line::findOne($line_id);
    }
}