<?php namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "line".
 *
 * @property int $id
 * @property int $status
 * @property int $driver_id
 * @property int $vehicle_id
 * @property float $tariff
 * @property int $route_id
 * @property int $startpoint
 * @property int $endpoint
 * @property int $seats
 * @property int $freeseats
 * @property int $starttime
 * @property int $endtime
 * @property string $cancel_reason
 * @property int $created_at
 * @property int $updated_at
 */
class Line extends \yii\db\ActiveRecord
{
    const
        STATUS_ACTIVE = 1,
        STATUS_DISABLED = 0,
        STATUS_CANCELED = 0,
        STATUS_WAITING = 1,
        STATUS_IN_PROGRESS = 2,
        STATUS_FINISHED = 3;

    public static function tableName()
    {
        return 'line';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className()
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [
                [
                    'driver_id',
                    'vehicle_id',
                    'status',
                    'route_id',
                    'seats',
                    'freeseats',
                    'startpoint',
                    'endpoint',
                    'tariff'
                ],
                'required'
            ],

            [
                [
                    'status',
                    'driver_id',
                    'vehicle_id',
                    'route_id',
                    'startpoint',
                    'endpoint',
                    'seats',
                    'freeseats'
                ],
                'integer'
            ],

            [
                [
                    'tariff'
                ],
                'number'
            ],

            [
                [
                    'cancel_reason'
                ],
                'string'
            ],

            [
                [

                    'starttime',
                    'endtime'
                ],
                'safe'
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'                => Yii::t('app', "ID"),
            'driver_id'         => Yii::t('app', "Водитель"),
            'vehicle_id'        => Yii::t('app', "Автомобиль"),
            'route_id'          => Yii::t('app', "Маршрут"),
            'startpoint'        => Yii::t('app', "Начальная точка"),
            'endpoint'          => Yii::t('app', "Конечная точка"),
            'tariff'            => Yii::t('app', "Тариф"),
            'status'            => Yii::t('app', "Статус"),
            'seats'             => Yii::t('app', "Мест"),
            'freeseats'         => Yii::t('app', "Свободных мест"),
            'starttime'         => Yii::t('app', "Время отправления"),
            'endtime'           => Yii::t('app', "Время прибытия"),
            'cancel_reason'     => Yii::t('app', "Причина отмены"),
            'created_at'        => Yii::t('app', "Создано"),
            'updated_at'        => Yii::t('app', "Обновлено")
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        if ($this->freeseats == 0)
        {
            // TODO: Отправка в сокет что машина заполнена и подтверждение о выезде через 5 минут
        }

        if ($this->status == self::STATUS_IN_PROGRESS && $this->getOldAttribute('status') != self::STATUS_IN_PROGRESS)
        {
            // TODO: Отправлять уведомление о выезде
        }
    }
}
